services:
  backend:
    build:
      context: ./BookStore_Backend
      dockerfile: Dockerfile
    ports:
      - "5206:5206"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BookStore__XmlFilePath=/data/books.xml
    volumes:
      - ./data/books.xml:/data/books.xml

  frontend:
    build:
      context: ./bookstore_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
